# Generated by Django 5.1.2 on 2024-11-29 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comp_num', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=200)),
                ('street', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=10)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Financial year')),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_on_analysis.addon')),
            ],
        ),
        migrations.AddField(
            model_name='addon',
            name='activities',
            field=models.ManyToManyField(to='add_on_analysis.nace'),
        ),
        migrations.AddField(
            model_name='addon',
            name='vertex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_on_analysis.vertex'),
        ),
    ]
