# Generated by Django 5.1.2 on 2024-11-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_on_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='vertex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_on_analysis.vertex'),
        ),
    ]
