# Generated by Django 5.1.2 on 2024-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_on_analysis', '0002_alter_addon_vertex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_data',
            old_name='fte',
            new_name='bezoldigingen',
        ),
        migrations.AddField(
            model_name='fin_data',
            name='afschrijvingen',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fin_data',
            name='eigen_vermogen',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fin_data',
            name='fin_kosten',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fin_data',
            name='liq_middelen',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fin_data',
            name='mva',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fin_data',
            name='schuld_hoogst_1j',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fin_data',
            name='schuld_meer_1j',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fin_data',
            name='winst_verlies',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fin_data',
            name='winst_verlies_v_belasting',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
    ]
