# Generated by Django 5.1.2 on 2024-12-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_on_analysis', '0004_remove_fin_data_ebitda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='comp_num',
            field=models.CharField(default='', max_length=200),
        ),
    ]
