# Generated by Django 5.1.2 on 2024-12-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_on_analysis', '0005_alter_addon_comp_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='bezoldigingen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='capex_noden_avg_3j',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='ebitda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='eigen_vermogen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='mva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='netto_schuldpositie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='winst_verlies',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
