# Generated by Django 5.1.2 on 2025-02-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_on_analysis', '0006_addon_bezoldigingen_addon_capex_noden_avg_3j_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='bezoldigingen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BEZ.'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='ebitda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EBITDA'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Naam'),
        ),
    ]
