# Generated by Django 5.1.2 on 2025-03-24 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('street', models.CharField(db_index=True, max_length=255)),
                ('house_number', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['street', 'house_number', 'city'], name='companies_a_street_e5f0b0_idx')],
            },
        ),
    ]
