# Generated by Django 5.1.2 on 2025-03-28 03:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='company_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='company',
            index=django.contrib.postgres.indexes.GinIndex(fields=['number'], name='company_number_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
