# Generated by Django 5.1.2 on 2025-03-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='maps_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
