# Generated by Django 5.1.2 on 2025-03-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='enterprise_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
