# Generated by Django 5.1.2 on 2025-03-28 15:41

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_name_trgm_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='company_name_trgm',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_number_trgm',
        ),
        migrations.AddField(
            model_name='company',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(models.F('search_vector'), name='company_search_vector_idx'),
        ),
    ]
