# Generated by Django 5.1.2 on 2025-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_address_street_alter_company_enterprise_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
