# Generated by Django 5.1.2 on 2025-03-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_maps_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='maps_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
