# Generated by Django 5.1.2 on 2025-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_address_city_alter_address_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=20),
        ),
    ]
