# Generated by Django 5.1.2 on 2025-03-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_maps_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='companies_a_street_e5f0b0_idx',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street', 'postal_code', 'house_number'], name='companies_a_street_98d30c_idx'),
        ),
    ]
