# Generated by Django 5.1.2 on 2025-03-25 03:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_address_companies_a_street_e5f0b0_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='company_name_lower_idx'),
        ),
    ]
