# Generated by Django 5.1.2 on 2025-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_address_house_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street', 'postal_code', 'city'], name='companies_a_street_21ce26_idx'),
        ),
    ]
