# Generated by Django 5.1.2 on 2025-03-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_company_search_vector_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='company_search_vector_idx',
        ),
        migrations.RemoveField(
            model_name='company',
            name='search_vector',
        ),
    ]
