# Generated by Django 5.1.2 on 2025-03-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_address_companies_a_street_21ce26_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='companies_a_street_21ce26_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street', 'postal_code', 'house_number', 'city'], name='companies_a_street_7f2434_idx'),
        ),
    ]
