# Generated by Django 5.1.2 on 2025-03-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_company_search_vector_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='mandate',
        ),
    ]
