# Generated by Django 5.1.2 on 2025-04-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_administrator_mandate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='administering_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrator_of', to='companies.company'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AnnualAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='companies.annualaccount')),
                ('held_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_by', to='companies.company')),
            ],
        ),
    ]
