# Generated by Django 5.1.2 on 2025-03-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_address_companies_a_street_21ce26_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='companies_a_street_7f2434_idx',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street', 'house_number', 'city'], name='companies_a_street_e5f0b0_idx'),
        ),
    ]
