# Generated by Django 5.1.2 on 2025-03-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_person_annualaccount_codelabel_financialrubric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualaccount',
            old_name='end_year',
            new_name='end_fiscal_year',
        ),
    ]
