# Generated by Django 5.1.2 on 2025-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_rename_end_year_annualaccount_end_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='person',
        ),
        migrations.AddField(
            model_name='administrator',
            name='representatives',
            field=models.ManyToManyField(related_name='roles', to='companies.person'),
        ),
        migrations.AlterField(
            model_name='financialrubric',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
