# Generated by Django 5.1.2 on 2025-04-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_administrator_administering_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='AnnualAccount',
            new_name='annual_account',
        ),
    ]
