# Generated by Django 5.1.2 on 2025-03-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_rename_end_year_annualaccount_end_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='administered_company',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='person',
        ),
        migrations.AddField(
            model_name='administrator',
            name='annual_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='companies.annualaccount'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='representatives',
            field=models.ManyToManyField(related_name='roles', to='companies.person'),
        ),
        migrations.AlterField(
            model_name='annualaccount',
            name='end_fiscal_year',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialrubric',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
