# Generated by Django 5.1.2 on 2025-03-28 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_administrator_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='administered_company',
        ),
        migrations.AddField(
            model_name='administrator',
            name='annual_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='companies.annualaccount'),
        ),
        migrations.AlterField(
            model_name='annualaccount',
            name='end_fiscal_year',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
