# Generated by Django 5.1.2 on 2025-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_administrator_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualaccount',
            name='end_fiscal_year',
            field=models.DateField(),
        ),
    ]
