# Generated by Django 5.1.2 on 2025-03-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_annualaccount_end_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='administered_company',
        ),
        migrations.AddField(
            model_name='administrator',
            name='annual_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='companies.annualaccount'),
            preserve_default=False,
        ),
    ]
