# Generated by Django 5.1.2 on 2025-03-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_remove_administrator_administered_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualaccount',
            name='end_fiscal_year',
        ),
    ]
