# Generated by Django 5.1.2 on 2025-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
