# Generated by Django 5.1.2 on 2025-03-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_annualaccount_end_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualaccount',
            name='end_fiscal_year',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
