# Generated by Django 5.1.2 on 2025-04-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_legal_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='type',
            new_name='enterprise_type_code',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='legal_form',
            new_name='legalform_code',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='status',
            new_name='status_code',
        ),
    ]
