# Generated by Django 5.1.2 on 2025-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_municipality_list_municipality_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='municipality_scores',
            field=models.JSONField(default=dict),
        ),
    ]
